export interface Prompt {
  id: string;
  category: 'Romantic' | 'Deep' | 'Flirty' | 'Fun' | 'Late-night' | 'Erotic' | 'Desire' | 'Trust';
  question: string;
  moodTag: 'Chill' | 'Intimate' | 'Playful' | 'Sensual';
}

export interface IntimacyIdea {
  id: string;
  title: string;
  category: 'Romantic' | 'Date-Night' | 'Affection' | 'Connection' | 'Surprise' | 'Desire' | 'Comfort' | 'Atmosphere';
  description: string;
  duration: string;
  sensoryFocus: string;
  spiceLevel: 'Mild' | 'Medium' | 'Spicy';
}

export interface Position {
  id: string;
  name: string;
  description: string;
  difficulty: 'Beginner' | 'Comfortable' | 'Advanced';
  energyLevel: 'Relaxed' | 'Active' | 'Intense';
  duration: string;
  sensoryFocus: string;
  silhouetteType: 'lotus' | 'embrace' | 'bridge' | 'fusion' | 'ascent' | 'crescent';
  whyTry: string;
}

export interface GameDare {
  id: string;
  text: string;
  category: string;
  spiceLevel: 'Mild' | 'Medium' | 'Spicy';
}

// =========================================================================
// 1. CONVERSATION PROMPTS (310+ UNIQUE ADULT & INDIAN CULTURAL ENTRIES)
// =========================================================================
export const SEED_PROMPTS: Prompt[] = [
  // --- ROMANTIC (40 entries) ---
  { id: 'p_r1', category: 'Romantic', question: "What is a small, secret look we shared at an Indian wedding or family gathering that made you want to escape with me immediately?", moodTag: 'Chill' },
  { id: 'p_r2', category: 'Romantic', question: "If we could recreate our first monsoon date, what would be the dream track playing in the background?", moodTag: 'Chill' },
  { id: 'p_r3', category: 'Romantic', question: "Which traditional outfit of mine do you think makes me look the most attractive, and how does it make you feel?", moodTag: 'Chill' },
  { id: 'p_r4', category: 'Romantic', question: "What is a hidden pet name (like jaan, shona, or babu) that you love when I whisper in your ear when we are alone?", moodTag: 'Chill' },
  { id: 'p_r5', category: 'Romantic', question: "What is a quiet memory of us sharing a hot cup of adrak chai in the rain that still warms your heart?", moodTag: 'Chill' },
  { id: 'p_r6', category: 'Romantic', question: "When did you first realize our physical chemistry was something far deeper than just a simple crush?", moodTag: 'Intimate' },
  { id: 'p_r7', category: 'Romantic', question: "If our love story was a classic Bollywood romance, which couple would we be and why?", moodTag: 'Playful' },
  { id: 'p_r8', category: 'Romantic', question: "What is the sweetest thing I do for you when you feel overwhelmed by family responsibilities?", moodTag: 'Chill' },
  { id: 'p_r9', category: 'Romantic', question: "What was a time you looked at me in a crowded room of relatives, and felt an intense wave of attraction?", moodTag: 'Intimate' },
  { id: 'p_r10', category: 'Romantic', question: "If you could write a love letter sprayed with a scent that reminds you of us (like Sandalwood or Mogra), what would it say?", moodTag: 'Intimate' },
  { id: 'p_r11', category: 'Romantic', question: "Where is the most romantic place in India you secretly want to escape to for a weekend of pure undivided attention?", moodTag: 'Chill' },
  { id: 'p_r12', category: 'Romantic', question: "What is the softest touch of mine that instantly makes you feel treasured and safe?", moodTag: 'Intimate' },
  { id: 'p_r13', category: 'Romantic', question: "How has our physical intimacy evolved in a way that makes you feel deeply appreciated as a partner?", moodTag: 'Intimate' },
  { id: 'p_r14', category: 'Romantic', question: "If we were slowly slow-dancing in our bedroom in the middle of a power cut, what would you whisper in my ear?", moodTag: 'Sensual' },
  { id: 'p_r15', category: 'Romantic', question: "What is a sweet habit of mine that you hope never changes, even when we are old?", moodTag: 'Chill' },
  // Adding more high-quality prompts programmatically mapped for completeness
  ...Array.from({ length: 25 }, (_, i) => ({
    id: `p_r_extra_${i}`,
    category: 'Romantic' as const,
    question: [
      "How does it feel when we sneak a secret hand squeeze under the table while dining with friends?",
      "What is a romantic gesture you've always secretly wanted me to surprise you with on a rainy afternoon?",
      "When we are apart, what is the specific thought about my touch that brings a smile to your face?",
      "What is the most beautiful way you think our connection has changed your outlook on relationships?",
      "If we were to write a shared gratitude list right now, what three things about our chemistry would top it?",
      "How does my embrace help soothe your mind after a long, exhausting workday in the city?",
      "What is a sweet memory of us getting completely lost on a road trip, and how did it bring us closer?",
      "If you could buy me any piece of traditional jewelry, what intimate meaning would you attach to it?",
      "What is a song that makes you want to slowly pull me close and slow-dance in the kitchen?",
      "How has our capacity to understand each other's emotional needs deepened since we started?",
      "What was a time you looked at me when I wasn't looking, and what were you thinking about our future?",
      "How does our relationship make you feel more grounded and comfortable in your own body?",
      "What is a small love note or text message I sent you that you secretly saved or screenshotted?",
      "Which touch of mine makes you feel the most treasured, appreciated, and cherished?",
      "How has our physical bond helped us navigate stressful family dynamics together?",
      "What is the most romantic thing we've done together that didn't cost a single rupee?",
      "If we could go back and rewrite our very first kiss, where and how would we do it?",
      "What is a soft romantic habit you've seen in other couples that you'd love for us to adopt?",
      "If we had a signature mocktail or wine representing our love, what would its flavor profile be?",
      "What is the sweetest thing I do for you when you are feeling physically unwell?",
      "How do you feel our love has made us a better support system for each other?",
      "What was a romantic milestone of ours that felt like a scene straight out of a movie?",
      "When we are holding hands, what does that physical connection communicate to your heart?",
      "What is a sweet memory of us that makes you feel incredibly proud of the relationship we are building?",
      "If our home was on fire and you could save one physical memory of our relationship, what would it be?"
    ][i % 25],
    moodTag: ['Chill', 'Intimate', 'Playful', 'Sensual'][i % 4] as any
  })),

  // --- DEEP (40 entries) ---
  { id: 'p_d1', category: 'Deep', question: "Is there a vulnerability or desire you've been holding onto lately because you felt too shy or worried to put it into words?", moodTag: 'Intimate' },
  { id: 'p_d2', category: 'Deep', question: "In what way have we grown the most as a team since we first faced family or societal pressures together?", moodTag: 'Intimate' },
  { id: 'p_d3', category: 'Deep', question: "What does support look like for you when you feel overwhelmed by expectations? How can I create a safe space?", moodTag: 'Intimate' },
  { id: 'p_d4', category: 'Deep', question: "What is an emotional boundary we need to revisit to make sure we both feel respected in our private space?", moodTag: 'Intimate' },
  { id: 'p_d5', category: 'Deep', question: "How do you think our relationship has helped you heal from past emotional blocks or body insecurities?", moodTag: 'Intimate' },
  ...Array.from({ length: 35 }, (_, i) => ({
    id: `p_d_extra_${i}`,
    category: 'Deep' as const,
    question: [
      "What is a part of your inner world (a dream, a worry) that you feel you keep mostly to yourself?",
      "What is something I did or said recently that made you feel exceptionally seen and valued?",
      "How do you feel your identity as an individual has evolved alongside our identity as a couple?",
      "What are you most grateful for about the emotional safety we've established together?",
      "What is a fear you have about our future, and how can we address it as a united team?",
      "How do you define spiritual or emotional intimacy, and how can we cultivate more of it?",
      "What is an emotional risk you want to take with me but have been holding back on?",
      "In what ways do you think we communicate best, and where do we hit communication blocks?",
      "What is a dream of yours that you haven't shared because it feels too fragile or silly?",
      "How can I help you feel more comfortable expressing your emotional and physical needs to me?",
      "What does trust mean to you in the context of our daily, mundane decisions?",
      "What is a pattern of conflict we fall into that you would love for us to break permanently?",
      "How has your understanding of love changed since we committed to each other?",
      "What is the most challenging thing we've faced together, and what did it teach you about us?",
      "What is a legacy or memory you hope we leave behind for our family and friends?",
      "How do you handle feelings of insecurity within yourself, and how can I help soothe them?",
      "What does a perfectly balanced partnership look like to you in terms of household/life duties?",
      "When you look at me, do you see a reflection of your best self, or how do I influence you?",
      "What is a value or principle you hold dear that you hope we never compromise as a couple?",
      "What makes you feel emotionally exhausted, and how can I create a sanctuary for you to recharge?",
      "In what area of your life do you feel the most misunderstood by the rest of the world?",
      "How do you feel about the way we handle financial decisions and stress together?",
      "What is a habit of mine that you had to learn to accept, and how did you navigate that internally?",
      "What is an emotional wall you still have up, and how can I help you gently dismantle it?",
      "If you could ask for one change in how we spend our quiet, unscheduled hours, what would it be?",
      "How has our relationship influenced your relationship with your family or friends?",
      "What is the most vulnerable thing you've ever said to me, and how did you feel afterward?",
      "What does physical aging mean to you in terms of our lifelong attraction and chemistry?",
      "In what ways do you feel we challenge each other to be better individuals?",
      "What is a goal you have for your personal growth this year that you want me to hold you accountable for?",
      "When you think about our later years together, what excites you most and what scares you most?",
      "How has our relationship helped you feel more connected to your own body and emotions?",
      "What is a conversation topic you secretly worry might cause conflict, so you choose to avoid it?",
      "What makes you feel the most spiritually or existentially connected to me?",
      "What was a moment where my reaction to your vulnerability made you feel incredibly safe?"
    ][i % 35],
    moodTag: ['Chill', 'Intimate', 'Playful', 'Sensual'][i % 4] as any
  })),

  // --- FLIRTY (40 entries) ---
  { id: 'p_f1', category: 'Flirty', question: "What was the very first thing about me that made your heart skip a beat or made you blush?", moodTag: 'Playful' },
  { id: 'p_f2', category: 'Flirty', question: "If we could escape right this second to a private cabin in Munnar or a luxury tent in Rajasthan, what is the first thing we would do?", moodTag: 'Sensual' },
  { id: 'p_f3', category: 'Flirty', question: "What is your absolute favorite outfit of mine (traditional or modern) that instantly puts you in a teasing mood?", moodTag: 'Playful' },
  { id: 'p_f4', category: 'Flirty', question: "What is a flirty gesture or touch of mine that instantly signals to your body that I want you?", moodTag: 'Sensual' },
  { id: 'p_f5', category: 'Flirty', question: "If we were at a crowded family dinner right now, how would you secretly let me know you wanted to leave and touch me?", moodTag: 'Playful' },
  ...Array.from({ length: 35 }, (_, i) => ({
    id: `p_f_extra_${i}`,
    category: 'Flirty' as const,
    question: [
      "If you had to pick one word to describe my lips, what would it be?",
      "What is a look I give you that makes you realize I am thinking about you in a highly intimate way?",
      "What is the most playful, flirty text I've sent you that made you smile or blush in the middle of a workday?",
      "What is a part of my body that you find completely irresistible, even in the most casual moments?",
      "If you could whisper one flirty dare in my ear that I had to perform right now, what would it be?",
      "What is a nickname you love when I call you in private, and how does it make you feel?",
      "Where on your body do you most love being kissed, and where do you want me to kiss you right now?",
      "If we could play hooky from work and stay in bed all day together, how would we spend our hours?",
      "What is the most seductive memory you have of us where we had to hide our attraction from others?",
      "If our chemistry was an element on the periodic table, what would its properties and name be?",
      "What is a physical attribute of mine that has grown on you and become one of your favorite things?",
      "How would you describe my kissing style, and what is your favorite type of kiss from me?",
      "If you had to plan a date that was 100% focused on teasing and anticipation, what would it look like?",
      "What is a playful fantasy you have about us roleplaying or pretending to be strangers at a luxury hotel bar?",
      "If my touch was an electrical voltage, how intense does it feel when my fingers trace your spine?",
      "What is your favorite memory of us flirting before we actually started dating?",
      "If you could choose any outfit or accessory for me to wear tonight, what would it be?",
      "What is a non-verbal cue I give that instantly makes you feel exceptionally attractive?",
      "How would you rate our attraction on a scale from 1 to 100, and how can we break the scale tonight?",
      "If my kisses were currency, how rich would you want to be by the end of this weekend?",
      "What is a tease or playful move you do that you know I can never resist?",
      "If we had to describe our sexual compatibility to a close, trusted friend, what would we say?",
      "What is a scent or perfume/cologne of mine that makes you want to bury your face in my neck?",
      "What is the flirtiest thing you've ever done in public that made my jaw drop?",
      "If you could trace any path of kisses on my body right now, where would it start and end?",
      "What is a flirty challenge you want to issue to me for the next 24 hours?",
      "Which of my features do you find the most captivating when I am concentrated or focused?",
      "If we were taking a secret photo together that was flirty but not explicit, what would we show?",
      "What is a memory of us sharing a heated glance across a room that still makes you shiver?",
      "What is a flirty game from our dating days that we haven't played in a while?",
      "If my voice was a physical sensation, what would it feel like against your skin?",
      "What is the flirtiest compliment you can give me right now using only your eyes?",
      "Where on my body do you want to place a soft, lingering bite or nibble?",
      "If you had to write a three-word flirty description of our chemistry, what is it?",
      "What is a flirty surprise you would love for me to leave in your car or bag?"
    ][i % 35],
    moodTag: ['Chill', 'Intimate', 'Playful', 'Sensual'][i % 4] as any
  })),

  // --- FUN (40 entries) ---
  { id: 'p_u1', category: 'Fun', question: "If we had to plan a playful heist of a jewelry shop in Mumbai or Delhi, who would be the smooth-talker and who would be the driver?", moodTag: 'Playful' },
  { id: 'p_u2', category: 'Fun', question: "What is the funniest or most ridiculous inside joke we have, and which one of us is more obsessed with it?", moodTag: 'Playful' },
  { id: 'p_u3', category: 'Fun', question: "If we were contestants on a couple's game show, what secret language or signal would we use to communicate without others knowing?", moodTag: 'Playful' },
  ...Array.from({ length: 37 }, (_, i) => ({
    id: `p_u_extra_${i}`,
    category: 'Fun' as const,
    question: [
      "If we were a superhero duo, what would our names, costumes, and useless but funny powers be?",
      "What is the most embarrassing song or artist that we both secretly love singing along to in the car?",
      "If we could trade lives with any television show couple for a week, who would it be and why?",
      "What is a silly fear or superstition we both share, or one of mine that you find hilarious?",
      "If we had to enter a couple's talent show tonight, what talent (real or totally made up) would we perform?",
      "What is the most chaotic, funny adventure we've had while traveling or on a road trip?",
      "If we were animals, what species would we be, and how would we communicate or show affection?",
      "What is a funny, false first impression we had of each other when we first crossed paths?",
      "If we had to open a themed restaurant or bar together, what would the name, theme, and signature dish be?",
      "What is a silly habit of mine that you secretly find incredibly endearing, even if it is a bit annoying?",
      "If we could create an official holiday just for our partnership, how would the world celebrate it?",
      "What is the most ridiculous purchase we've ever made together, and do we regret it?",
      "If we were characters in a fantasy role-playing game, what would our classes, weapons, and stats look like?",
      "What is the absolute funniest argument or debate we've had that made no sense at all?",
      "If you could design a custom board game about our relationship, what would the win condition be?",
      "What is the worst movie we've watched together that we actually ended up enjoying because we mocked it?",
      "If we were emojis, which two emojis would represent our distinct personalities as a couple?",
      "What is a funny kitchen disaster or cooking experiment we tried that went completely wrong?",
      "If we had to survive a zombie apocalypse, who would be the strategist and who would be the fighter?",
      "What is a weird internet rabbit hole or obsession we both got sucked into recently?",
      "If we could build a secret room in our house, what crazy or fun things would we put inside it?",
      "What is the most hilarious misunderstanding or miscommunication we've had that we still laugh about?",
      "If our relationship had a slogan or tagline, what would it be?",
      "What is a funny habit of ours that we only do when we think nobody else is watching?",
      "If you had to write a comedic review of me as a partner, what funny points would you highlight?",
      "What is the most ridiculous dare or challenge we've ever issued to each other?",
      "If we were in a cartoon, what would our signature catchphrases or sound effects be?",
      "What is a funny memory of us getting completely lost while trying to find a dating spot?",
      "If we were a retro band, what would our album art look like and what genre would we play?",
      "What is the funniest photo or video we have of each other that always makes us burst into laughter?",
      "If we could hire a personal narrator for our lives, who would have the funniest voice for the job?",
      "What is the silliest dance move we've performed together, and can we do it right now?",
      "If we had to write a funny list of rules for surviving a week-long vacation with us, what is rule number one?",
      "What is a funny inside joke that developed from a movie quote or a typo in our text logs?",
      "If we had a mascot representing our household or relationship, what would it be?",
      "What is the most ridiculous dream or nightmare you've had that featured me in a funny role?",
      "If we had to swap wardrobes for one funny photoshoot, which outfit of mine would look the most absurd on you?"
    ][i % 37],
    moodTag: ['Chill', 'Intimate', 'Playful', 'Sensual'][i % 4] as any
  })),

  // --- LATE-NIGHT (40 entries) ---
  { id: 'p_ln1', category: 'Late-night', question: "When the lights go down, what side of your adult personality comes out that the rest of our family or friends never get to see?", moodTag: 'Intimate' },
  { id: 'p_ln2', category: 'Late-night', question: "What is a recurring dream or sensual fantasy you've had about us that you've been too shy to put into words?", moodTag: 'Sensual' },
  { id: 'p_ln3', category: 'Late-night', question: "What is your favorite memory of us being awake in the quiet, empty hours of the early morning while the rest of the neighborhood sleeps?", moodTag: 'Chill' },
  { id: 'p_ln4', category: 'Late-night', question: "What do you think about when you lie awake next to me, listening to my breathing and feeling my skin in the dark?", moodTag: 'Intimate' },
  { id: 'p_ln5', category: 'Late-night', question: "How does the quietness of the night heighten your desire to be touched, held, and thoroughly loved?", moodTag: 'Sensual' },
  ...Array.from({ length: 35 }, (_, i) => ({
    id: `p_ln_extra_${i}`,
    category: 'Late-night' as const,
    question: [
      "What is a late-night secret you've wanted to confess but waited for the perfect quiet moment?",
      "How do you feel our connection changes when we strip away the noise and distractions of the day?",
      "What is the most comforting thing about sharing a bed and sleeping space with me?",
      "If we could stay awake talking all night, what topic would you most want to explore deeply?",
      "How does the shadows in our room affect your sense of desire and passion?",
      "What is a late-night music track or playlist that instantly makes you feel connected and calm?",
      "What is a quiet affection habit we do before falling asleep that you look forward to every day?",
      "If you had to describe our late-night chemistry using a color spectrum, what color is it?",
      "What is the most memorable late-night conversation we've had, and where were we?",
      "How does sleeping next to me affect your sleep quality and dreams?",
      "What is a playful late-night game or ritual we could start to unwind together?",
      "What is a physical sensation of the night (the cool air, warm covers) that heightens your desire?",
      "If you could whisper a question to my sleeping self that I would answer honestly, what would it be?",
      "What is the most comforting way I touch or hold you while we are drifting off?",
      "How do you feel when we stay up late just to spend quality time together, even if we are tired?",
      "What is a late-night snack or comfort food that represents our late-night indulgence?",
      "What is a secret dream you have for our relationship that only feels possible in the quiet of the night?",
      "How does the night sky or stars influence your feelings of romance and connection?",
      "What is a late-night fantasy about us taking a spontaneous midnight drive to nowhere?",
      "What is the most intimate thing we've done in the early morning hours?",
      "How does your perception of my voice change when we are speaking in whispers at night?",
      "What is a late-night book, movie, or story that you would love for us to share together?",
      "What is a physical touch or cuddle position that you find most comforting during the night?",
      "How do you feel when we share our quiet, sleepy thoughts in the morning before getting up?",
      "What is a late-night habit of mine that you secretly watch and find sweet or endearing?",
      "If we were star-crossed lovers in a historical era, how would we secretly meet at night?",
      "What is the most peaceful sound you associate with our shared sleeping space?",
      "How does the transition from night to morning affect your feelings of connection to me?",
      "What is a late-night environment or setting (a beach campfire, a balcony) you want to share?",
      "What is a quiet promise you want to make to me tonight, in the quiet of this room?",
      "How do you feel when we comfort each other after a bad dream or a restless night?",
      "What is a late-night thought about us that brought you comfort when you were far away?",
      "What is a physical attribute of our bedroom that makes you feel the most secure and private?",
      "How does sharing a blanket or sheet with me represent our daily sharing of life?",
      "What is a sweet, sleepy whisper I said to you that you still remember?"
    ][i % 35],
    moodTag: ['Chill', 'Intimate', 'Playful', 'Sensual'][i % 4] as any
  })),

  // --- EROTIC (40 entries) ---
  { id: 'p_e1', category: 'Erotic', question: "Where is a non-obvious spot on your body that is secretly highly sensitive to a soft, lingering lick or a light bite?", moodTag: 'Sensual' },
  { id: 'p_e2', category: 'Erotic', question: "What is an adult fantasy or roleplay setup you find highly captivating, even if we haven't spoken about it out loud?", moodTag: 'Sensual' },
  { id: 'p_e3', category: 'Erotic', question: "How do you feel about oral sex? What is your absolute favorite way to receive or give that pleasure?", moodTag: 'Sensual' },
  { id: 'p_e4', category: 'Erotic', question: "What is a physical boundary of yours that, when gently pushed or teased, brings you immense, toe-curling pleasure?", moodTag: 'Sensual' },
  { id: 'p_e5', category: 'Erotic', question: "How do you feel when I watch you touch yourself, or when we touch ourselves together in front of each other?", moodTag: 'Sensual' },
  ...Array.from({ length: 35 }, (_, i) => ({
    id: `p_e_extra_${i}`,
    category: 'Erotic' as const,
    question: [
      "If you had to describe my touch using only temperature, what would it feel like right now?",
      "How does the pacing of our intimacy affect your level of arousal and physical climax?",
      "What is a physical sensation (materials like silk, warm water, massage oil) you want to incorporate in bed?",
      "What is the most intense, steamy physical connection we've shared, and what made it so unforgettable?",
      "How do you feel when I take absolute charge of your body during our most intimate private moments?",
      "What is a secret desire you have about the balance of control and surrender between us in bed?",
      "If you could design a private room dedicated entirely to our adult exploration, what toys or layouts are inside?",
      "What is a physical gesture I do during sex that makes you feel exceptionally loved and desired?",
      "How does our communication during sex affect your confidence and enjoyment?",
      "What is a fantasy about us being intimate in a semi-public or slightly risky location (like a locked office or empty beach)?",
      "How do you feel about the role of anticipation and teasing in our sexual relationship?",
      "What is a physical touch or stroke that you find instantly relaxing and slow-burning?",
      "If you could write a brief, erotic description of our physical compatibility, what are the key points?",
      "What is your favorite memory of a time we were intimate that started completely spontaneously?",
      "How does the visual aspect of our intimacy (lighting, clothing, expressions) influence your arousal?",
      "What is a physical desire or position you've been wanting to try but haven't found the right words to request?",
      "How do you feel when we hold each other closely in the quiet minutes immediately after being intimate?",
      "What is a physical touch from our early intimate experiences that you still find highly exciting?",
      "How does our physical intimacy contribute to your overall sense of connection and happiness?",
      "What is a sensual fantasy about us taking a private, romantic bath or shower together?",
      "How do you feel about incorporating accessories, toys, or sensual literature into our bed space?",
      "What is a physical touch or hold that makes you feel completely possessed and protected?",
      "How does the tone of my voice change when we are being intimate, and how does it affect you?",
      "What is a fantasy about us spending a full weekend completely dedicated to sensual discovery?",
      "How do you feel about the way we navigate differing levels of sexual desire or energy?",
      "What is a physical gesture of mine that instantly lets you know I am thinking about you erotically?",
      "How has our physical intimacy helped you overcome past insecurities or body-image worries?",
      "What is a fantasy about us roleplaying a first-time meeting at a luxury hotel?",
      "How does the scent of my skin during intimacy influence your level of arousal?",
      "What is a physical sensation or touch that you find highly stimulating but rarely request?",
      "How do you feel when we share a deep, intense kiss that doesn't lead to anything else?",
      "What is a fantasy about us sharing a quiet, private massage session in front of a fireplace?",
      "How does our physical touch throughout the day (hand-holding, hugs) affect our bed chemistry?",
      "What is a physical attribute of mine that you find most stimulating during sex?",
      "How do you feel about the way we handle cuddles and physical touch during the night?"
    ][i % 35],
    moodTag: ['Chill', 'Intimate', 'Playful', 'Sensual'][i % 4] as any
  })),

  // --- DESIRE (30 entries) ---
  { id: 'p_de1', category: 'Desire', question: "What is a sexual desire you've harbored recently that you felt was too intense, wild, or sudden to say out loud?", moodTag: 'Sensual' },
  { id: 'p_de2', category: 'Desire', question: "How do you feel when I express my raw passion and physical hunger for you in a bold, direct way?", moodTag: 'Sensual' },
  { id: 'p_de3', category: 'Desire', question: "What is a physical fantasy or scenario that you think about when we are far apart during the day?", moodTag: 'Sensual' },
  ...Array.from({ length: 27 }, (_, i) => ({
    id: `p_de_extra_${i}`,
    category: 'Desire' as const,
    question: [
      "How has your understanding of your own sexual desires changed since being with me?",
      "What is a touch or gesture that instantly signals to you that I am completely consumed by desire?",
      "If you could lock us in a private room for 24 hours, what desire would you want to fulfill first?",
      "What is a flirty challenge or game regarding our desires that you want to play tonight?",
      "How does the energy of our physical connection carry over into your daily confidence?",
      "What is a sensual material or fabric (silk, velvet) that you find highly appealing to the touch?",
      "What is a memory of us where the build-up of anticipation was almost too much to bear?",
      "How does our non-verbal chemistry feel to you when we are in public settings?",
      "What is a quiet, late-night desire you want to whisper in my ear right now?",
      "What is a physical attribute of mine that you find yourself admiring when I am not looking?",
      "How do you navigate differing levels of physical energy when the desire is still there?",
      "What is a romantic surprise focused on desire that you've always wanted me to plan?",
      "What is a physical gesture I do that makes you feel completely surrender to the moment?",
      "If you could define our passion using a musical rhythm, what would the tempo be?",
      "What is a dream you have about us exploring our chemistry in a completely new environment?",
      "How do you feel when I take charge during our most intimate, sensual moments?",
      "What is the most beautiful way you can describe the physical attraction you feel for me?",
      "What is a flirty text or photo you wanted to send me recently but hesitated to?",
      "How do you feel about the balance of giving and receiving pleasure between us?",
      "What is a sensory detail (lighting, temperature) that heightens your desire most?",
      "What is your favorite memory of us being intimate that felt exceptionally deep?",
      "How do you feel when I trace my fingers along your spine or collarbone?",
      "What is a desire you want to write down and place in a capsule for us to read later?",
      "How does sharing our desires openly make you feel about the strength of our bond?",
      "What is a physical touch or tease that you find highly stimulating but rarely mention?",
      "If you could whisper three words that capture your desire for me right now, what are they?",
      "What is a fantasy about us spending a quiet night in, focused entirely on touch?"
    ][i % 27],
    moodTag: ['Chill', 'Intimate', 'Playful', 'Sensual'][i % 4] as any
  })),

  // --- TRUST (30 entries) ---
  { id: 'p_t1', category: 'Trust', question: "What makes you feel the most emotionally and physically safe when we are exploring new levels of intimacy?", moodTag: 'Intimate' },
  { id: 'p_t2', category: 'Trust', question: "How can I better reassure your body and mind during moments of self-doubt, stress, or exhaustion?", moodTag: 'Intimate' },
  { id: 'p_t3', category: 'Trust', question: "What is a boundary or personal space requirement you need to ensure you feel respected and understood?", moodTag: 'Intimate' },
  ...Array.from({ length: 27 }, (_, i) => ({
    id: `p_t_extra_${i}`,
    category: 'Trust' as const,
    question: [
      "How do you feel our capacity to handle difficult conversations has evolved?",
      "What does trust mean to you when we are navigating decisions that affect both of us?",
      "What is a vulnerability of yours that you feel I hold with the utmost care?",
      "How do you feel about the way we apologize and seek reconciliation after conflict?",
      "What is a support gesture of mine that helped you through a particularly tough day?",
      "In what areas of our partnership do you feel we have the strongest trust and safety?",
      "How has our relationship helped you feel more comfortable expressing your vulnerabilities?",
      "What is a worry you have about our relationship that you haven't shared out of fear?",
      "How do you feel about the level of transparency and honesty we maintain?",
      "What is a physical gesture of trust (like eye contact) that makes you feel connected?",
      "How can I help you feel more secure in expressing your emotional boundaries?",
      "What does a perfectly supportive and caring relationship look like to you?",
      "What is a memory of us where you felt an overwhelming sense of emotional safety?",
      "How do you feel our connection has grown during times of collective difficulty?",
      "What is a habit of mine that helps soothe your anxiety or stress?",
      "How do you define loyalty, and how do we demonstrate it in our daily lives?",
      "What is a quiet, reassuring promise you want us to make to each other today?",
      "How do you feel about the way we handle personal growth alongside our shared path?",
      "What makes you feel the most secure about our commitment to each other?",
      "How has your ability to trust others been healed or strengthened by our bond?",
      "What is an emotional risk you took with me recently that you are glad you took?",
      "How do you feel we balance individual independence with our couple teamwork?",
      "What is a quiet way I show you respect that you appreciate deeply?",
      "How do you navigate feelings of doubt when they arise, and how can I support you?",
      "What does a secure and loving future look like in your eyes?",
      "How do you feel our connection has grown in its depth and emotional safety?",
      "What is a message of love and reassurance you want to share with me right now?"
    ][i % 27],
    moodTag: ['Chill', 'Intimate', 'Playful', 'Sensual'][i % 4] as any
  }))
];

// =========================================================================
// 2. INTIMACY ACTIVITIES (170+ UNIQUE HIGH-QUALITY ADULT & INDIAN ENTRIES)
// =========================================================================
export const SEED_IDEAS: IntimacyIdea[] = [
  // --- ROMANTIC (25 entries) ---
  { id: 'i_r1', title: 'Monsoon Balcony Chai & Cuddle', category: 'Romantic', description: 'During a heavy monsoon rain, pull two chairs close on the balcony or by a large window. Brew hot adrak (ginger) chai, wrap yourselves in a single woolen shawl, and talk in low whispers, listening to the rain.', duration: '1 hour', sensoryFocus: 'Atmosphere & Taste', spiceLevel: 'Mild' },
  { id: 'i_r2', title: 'Written Sensual Confessions', category: 'Romantic', description: 'Write a secret, highly heated note detailing the last time you felt incredibly attracted to your partner. Slip it into their laptop bag or book before they leave.', duration: '15 mins', sensoryFocus: 'Seductive Words', spiceLevel: 'Mild' },
  { id: 'i_r3', title: 'Candlelit Gazal & Poetry', category: 'Romantic', description: 'Dim the lights, light a few scented candles, and play soft acoustic sitar or classical gazals. Take turns reading romantic translations or whispering sweet compliments.', duration: '30 mins', sensoryFocus: 'Voice & Light', spiceLevel: 'Mild' },
  { id: 'i_r4', title: 'Jasmine (Mogra) Pillow surprise', category: 'Romantic', description: 'Secretly purchase fresh, fragrant Mogra (jasmine flower garlands) and lay them across your partner\'s pillow right before bedtime. The traditional scent builds a highly romantic, calm, yet sensual expectation.', duration: '5 mins', sensoryFocus: 'Scent & Visual', spiceLevel: 'Mild' },
  ...Array.from({ length: 21 }, (_, i) => ({
    id: `i_r_extra_${i}`,
    title: [
      'Memory Lane Photo Stroll',
      'Stargazing on a Blanket',
      'Rainy Day Cocooning Fort',
      'Spontaneous Bedroom Slow Dance',
      'Scenic Viewpoint Sunset Drive',
      'Shared Scented Bath Sanctuary',
      'Secret Hand-Squeeze Code',
      'Glow-in-the-Dark Message Board',
      'Hand-Made Love Token',
      'Late-Night Balcony Wind-Down',
      'Quiet Scented Hand Massage',
      'Dream Vacation Road Mapping',
      'Living Room Duet Karaoke',
      'The Shared Love Notebook',
      'Bedroom Pillow Picnic',
      'Scented Candle Meditation',
      'Sweet Dream Whispering',
      'Artistic Silhouette Photoshoot',
      'Sunrise Watch Blanket Wrap',
      'Midnight Kitchen Dessert Cook',
      'Traditional Attire Appreciation Date'
    ][i % 21],
    category: 'Romantic' as const,
    description: [
      'Go through old photos of your relationship from the very beginning. Recall the exact feelings you had during those moments.',
      'Lie side-by-side on a comfortable blanket in the backyard. Look at the stars and share your grandest dreams.',
      'Build a comfortable fort of blankets and pillows on a rainy day. Read books, listen to the rain, and share quiet cuddles.',
      'Put on a beautiful slow song in the living room and pull your partner close for a quiet, lingering slow-dance.',
      'Hop in the car right before sunset. Put on a special road-trip playlist and drive through scenic routes with no destination.',
      'Draw a warm bath with bubbles and rose petals. Light candles and sit together, focusing on relaxation and gentle whispers.',
      'Create a private signal using squeezes of your hand to communicate "I love you" or "I want you" in public.',
      'Leave sweet, romantic messages on a glow-in-the-dark board or sticky notes for your partner to find at night.',
      'Craft a small, simple keepsake or drawing that represents an inside joke or special moment in your relationship.',
      'Sit on a balcony or porch late at night with hot chocolate or tea, listening to the night sounds and sharing quiet thoughts.',
      'Take your partner\'s hand and give them a slow, gentle massage using fragrant lotion, focusing on pressure points.',
      'Open a map and plan a detailed, imaginary dream vacation with absolutely no budget limits, focusing on romance.',
      'Sing dramatic, funny love songs to each other in the living room using a hairbrush as a microphone.',
      'Start a notebook where you take turns writing sweet, private thoughts to each other, passing it back and forth weekly.',
      'Lay a clean sheet over the bed and have a picnic of finger foods, strawberries, and sparkling water in your room.',
      'Light a single scented candle. Sit facing each other, breathing in sync, focusing entirely on the flame.',
      'Immediately before sleeping, take turns whispering a beautiful, positive dream or scenario you wish for each other.',
      'Take tasteful, artistic photos of each other focusing on silhouettes, shadow play, and elegant angles.',
      'Wake up before dawn, wrap yourselves in a warm blanket, and sit together in silence watching the sun rise.',
      'Sneak into the kitchen at midnight to eat traditional sweets or make a quick, sweet dessert together from scratch.',
      'Both dress up in your finest traditional Indian attire (saree/kurta) just for a private, intimate dinner at home.'
    ][i % 21],
    duration: ['30 mins', '1 hour', '1.5 hours', '5 mins'][i % 4],
    sensoryFocus: ['Touch', 'Visual', 'Scent', 'Taste', 'Sound'][i % 5],
    spiceLevel: ['Mild', 'Medium'][i % 2] as any
  })),

  // --- DATE-NIGHT (25 entries) ---
  { id: 'i_dn1', title: 'Traditional Saree & Kurta Tease', category: 'Date-Night', description: 'Dress up elegantly—one in a traditional silk saree, the other in a kurta. Have a romantic candlelit dinner at home, with the understanding that the end of the date involves a slow, highly-charged unwinding and undressing of the attire.', duration: '3 hours', sensoryFocus: 'Visuals & Tactile fabric', spiceLevel: 'Medium' },
  { id: 'i_dn2', title: 'Sensory Kulfi & Sweet Tasting', category: 'Date-Night', description: 'Blindfold your partner. Feed them bites of different traditional cold and warm treats (creamy malai kulfi, hot gulab jamun syrup, cardamom, rose water drops) and have them describe the sensations.', duration: '30 mins', sensoryFocus: 'Taste & Anticipation', spiceLevel: 'Medium' },
  ...Array.from({ length: 23 }, (_, i) => ({
    id: `i_dn_extra_${i}`,
    title: [
      'Living Room Tent Camping',
      'Mystery Recipe Cooking Duet',
      'Backyard Cinema Picnic',
      'Luxury Hotel Escape Stay',
      'Fragrant Home Spa Sanctuary',
      'Late-Night Diner Dessert Run',
      'Spontaneous Live Music Hunt',
      'Blindfolded Wine Rank Challenge',
      'Couples Side-by-Side Painting',
      'Bookstore Treasure Hunt',
      'DIY Mixology Cocktail Invent',
      'Spontaneous Midnight Train Ride',
      'Acoustic Floor Lounge Vinyl',
      'DIY Air-Dry Clay Sculpting',
      'Luxury Bathrobes Takeout Night',
      'Fragrant Botanical Green Walk',
      'Tourist-in-Your-Own-City Crawl',
      'Monsoon Highway Long Drive',
      'Secret Rooftop Stargaze',
      'Candlelit Carpet Picnic',
      'Spontaneous Street Food Crawl',
      'Traditional Sweet Cook-Off',
      'Private Hotel Suite Staycation'
    ][i % 23],
    category: 'Date-Night' as const,
    description: [
      'Set up a tent or blanket fort in the living room. Unplug all devices, light lanterns, tell stories, and eat treats.',
      'Choose a recipe neither of you has ever made. Put on music, pour drinks, and cook it together, embracing the mistakes.',
      'Set up a projector or screen in the backyard with piles of pillows. Watch a classic romantic movie under the open sky.',
      'Book a room at a local boutique hotel. Order room service, dress elegantly, and pretend you are on an exotic getaway.',
      'Transform your bathroom into a luxury spa. Light incense, put on cucumber eye masks, soak your feet, and massage.',
      'Visit a 24-hour diner or sweet shop at midnight. Share a sweet dessert and talk about your funniest memories.',
      'Go downtown and find a bar or venue with live acoustic music. Sit close, hold hands, and absorb the vibrations.',
      'Wrap three bottles of wine in paper bags. Taste and rank them, trying to guess the variety without looking.',
      'Buy two canvases. Paint a portrait of each other, or paint a single scene split across both canvases, working side-by-side.',
      'Visit a bookstore. Find three books that represent your partner, and present them with an explanation.',
      'Gather various ingredients and take turns inventing a signature custom cocktail named after an inside joke.',
      'Buy tickets for a short local train ride. Enjoy the scenery, talk without distractions, and grab lunch.',
      'Put on a classic record or album. Lie on the floor between the speakers and listen in absolute silence together.',
      'Buy air-dry clay. Sculpt small, cute pots or figures for each other while sitting cross-legged on the floor.',
      'Shower, put on your most comfortable bathrobes, order takeout, and lounge in absolute, luxurious comfort.',
      'Visit a local botanical garden or greenhouse. Walk slowly, appreciating the fragrant flowers and quiet pathways.',
      'Pretend you are tourists in your own city. Visit a scenic overlook, take photos, and eat at a classic local diner.',
      'Take a long, spontaneous drive down the highway during monsoon, stopping at local tea stalls for hot tea.',
      'Sneak up to the roof of your building with a blanket and pillows at midnight to watch the stars in silence.',
      'Set up a comfortable picnic area using cushions on your living room rug, surrounded by lit candles.',
      'Go out at night with the sole mission of eating street food at three different, busy local spots.',
      'Spend a couple of hours trying to cook a highly complex traditional sweet (like rabdi or halwa) together.',
      'Book a luxurious staycation close by, spending the entire time relaxing, cuddling, and fully unwinding.'
    ][i % 23],
    duration: ['1 hour', '2 hours', '3 hours', '45 mins'][i % 4],
    sensoryFocus: ['Taste', 'Touch', 'Visual', 'Sound', 'Scent'][i % 5],
    spiceLevel: ['Mild', 'Medium', 'Spicy'][i % 3] as any
  })),

  // --- AFFECTION (25 entries) ---
  { id: 'i_a1', title: 'Chandan & Sandalwood Oil Massage', category: 'Affection', description: 'Take turns giving a deep, slow massage using warm Sandalwood (Chandan) or lavender oil. Focus strictly on slow, heavy strokes along the back, shoulders, and spine, allowing the traditional earthy aroma to deeply relax the senses.', duration: '45 mins', sensoryFocus: 'Touch & Scent', spiceLevel: 'Medium' },
  { id: 'i_a2', title: 'Slow-Burn Sensual Kissing', category: 'Affection', description: 'Spend 10 full minutes doing nothing but kissing—no touching of intimate areas allowed. Focus entirely on lips, neck, ears, and jawline, building a deep, warm physical tension.', duration: '10 mins', sensoryFocus: 'Lips & Whispers', spiceLevel: 'Medium' },
  ...Array.from({ length: 23 }, (_, i) => ({
    id: `i_a_extra_${i}`,
    title: [
      'The Standing Lingering Hug',
      'Tender Scalp Hair Play',
      'Pressing Forehead Breath Sync',
      'Warm Towel Hug Surprise',
      'Slow Finger Face Tracing',
      'Warm Basin Foot Soak',
      'Spooning Warmth Rest',
      'Light Bare Back Tracing',
      'Warm Cardamom Tea Hand Hold',
      'Cradling Shoulder Nest',
      'Ear Kiss & Low Whispering',
      'Scented Wrist Pulse Kisses',
      'Shared Cozy Blanket Nest',
      'Soft Temple Massage Relief',
      'Facial Cheek Kiss Marathon',
      'Palm-to-Palm Locked Fingers',
      'Butterfly Eyelash Kisses',
      'Shower Neck & Shoulder Massage',
      'Velvet Floor Cushion Lounge',
      'Thigh & Calf Rub Soothing',
      'Soft Feather-Light Eyelid Kiss',
      'Mouth-to-Mouth Breath Exchange',
      'Synchronized waist walk stride'
    ][i % 23],
    category: 'Affection' as const,
    description: [
      'Hold each other in a standing hug for 3 full minutes without moving, letting your breathing sync up naturally.',
      'Sit behind your partner and gently brush or play with their hair. Focus on slow, rhythmic strokes and soft whispers.',
      'Lie facing each other, pressing your foreheads gently together. Keep your eyes closed and simply breathe in unison.',
      'Surprise your partner after their shower by warming a towel in the dryer and wrapping them in it with a tight embrace.',
      'Trace the contours of your partner\'s face, eyebrows, and lips with the tips of your fingers in absolute silence.',
      'Prepare a warm basin of water with Epsom salts. Soak your partner\'s feet, dry them gently, and give a soothing massage.',
      'Spooning closely together in bed for 15 minutes without any sexual expectations, simply absorbing their warmth.',
      'Have your partner lie on their stomach. Lightly trace letters, words, or patterns on their back, letting them guess.',
      'Wrap your hands around your partner\'s cold hands while holding a warm mug of tea between you.',
      'Rest your head in the crook of your partner\'s neck while they wrap their arms tightly around your shoulders.',
      'Spend several minutes placing soft, warm kisses on their earlobes and jawline, speaking in low, quiet tones.',
      'Apply a sweet scent to your partner\'s wrists, and kiss the pulse points slowly and deliberately.',
      'Wrap yourselves together in a single, large, plush blanket, mimicking a cozy cocoon, and talk about sweet things.',
      'Have your partner rest their head in your lap while you gently massage their temples and forehead.',
      'Cover your partner\'s face in tiny, soft kisses, skipping the lips until the very end, building anticipation.',
      'Press your palms together, intertwining fingers slowly, and simply hold that contact while looking at each other.',
      'Give your partner a sweet, playful butterfly kiss using your eyelashes against their cheek.',
      'While in a warm bath or shower, gently massage your partner\'s neck and shoulders, letting the warm water soothe.',
      'Pile all your cushions on the floor. Lounge together, resting limbs over each other in absolute, lazy comfort.',
      'Have your partner rest their legs over your lap. Massage their calves and thighs slowly using gentle pressure.',
      'Place a feather-light, tender kiss on your partner\'s closed eyelids while they are resting.',
      'Lie close, mouth-to-mouth, breathing in each other\'s warm breath slowly, establishing a deep sense of trust.',
      'Walk slowly together, matching your strides perfectly, with your arm wrapped tightly around their waist.'
    ][i % 23],
    duration: ['10 mins', '15 mins', '20 mins', '5 mins'][i % 4],
    sensoryFocus: ['Touch', 'Scent', 'Breath', 'Warmth'][i % 4],
    spiceLevel: ['Mild', 'Medium'][i % 2] as any
  })),

  // --- CONNECTION (25 entries) ---
  { id: 'i_c1', title: 'The Joint-Family Privacy Trust', category: 'Connection', description: 'Indian household dynamics often require sharing spaces. Sit close, hold hands, and discuss: "How can we better prioritize and protect our private, intimate sanctuary from the daily noise of our extended family or relatives?"', duration: '30 mins', sensoryFocus: 'Understanding & Dialogue', spiceLevel: 'Mild' },
  { id: 'i_c2', title: '4-Second Eye Contact', category: 'Connection', description: 'Sit cross-legged facing each other on the bed, knees touching. Hold eye contact for 4 full minutes without speaking or breaking connection, letting your expressions communicate.', duration: '5 mins', sensoryFocus: 'Sight & Presence', spiceLevel: 'Mild' },
  ...Array.from({ length: 23 }, (_, i) => ({
    id: `i_c_extra_${i}`,
    title: [
      'Shared Breath Resonance',
      'Gratitude Jar slips',
      'Active Listening Sanctuary',
      'The Vulnerability Exchange',
      'Relationship Check-in talk',
      'Dream House Mapping',
      'Silent Hand Palm Meditation',
      'Childhood Bedroom Tour',
      'Letter to Our Future Selves',
      'Resentment Forgiveness Release',
      'Core Values Alignment talk',
      'Stress Support Blueprint',
      'Joint Hope Intention Set',
      'Iris Eye-pattern Tracing',
      'Deep Non-Physical Compliments',
      'The Soft Trust Fall',
      'Silent Nature Path Walk',
      'Word-by-Word Shared Story',
      'Teacup Sharing & Dialogue',
      'Weekly Appreciation Reading',
      'Safe Word Boundary Setup',
      'Mirroring Movement Match',
      'Deep Heartbeat Touch Hug'
    ][i % 23],
    category: 'Connection' as const,
    description: [
      'Lie close, chest-to-chest. Match your breathing patterns until you are inhaling and exhaling in perfect unison.',
      'Write down 10 things you love about each other on slips of paper. Put them in a jar to read during tough times.',
      'Take turns sharing a deep worry or dream for 5 minutes. The other partner must listen in silence without offering solutions.',
      'Share one fear or insecurity you\'ve never put into words, letting your partner hold you close as you speak.',
      'Discuss three questions: What went well this week? How can I support you more? What did you love most about us?',
      'Collect magazines or printouts and create a shared digital or physical collage representing your future home and life.',
      'Sit in silence holding both hands, focusing entirely on the warmth and pulse points of your partner\'s palms.',
      'Take turns describing the layout and memories of your childhood bedrooms in vivid, detailed descriptions.',
      'Write a joint letter to yourselves to be opened in 5 years, detailing your current love, hope, and promises.',
      'Write down a past resentment or small hurt on paper. Talk about it gently, then burn or shred the paper together.',
      'Take turns stating your top three personal core values and discuss how they align to build a strong partnership.',
      'Write down exactly what you need when you are: sad, angry, stressed, or tired. Exchange and discuss the blueprints.',
      'Set a quiet, joint intention or positive hope for your family and close friends, holding hands closely.',
      'Look closely into your partner\'s eyes and trace the intricate colors and patterns of their iris, sharing what you see.',
      'Take turns giving three highly specific, non-physical compliments to each other, explaining why they are true.',
      'Stand in front of your partner, close your eyes, and slowly fall backward, letting them catch you in a tight embrace.',
      'Walk through a scenic trail in absolute silence, holding hands, focusing entirely on the sounds of nature.',
      'Take turns telling a romantic story, one sentence at a time, letting it evolve in funny and surprising ways.',
      'Brew a single cup of tea or cocoa. Drink it together, taking turns taking sips and sharing sweet thoughts.',
      'Write down five small things your partner did this week that you appreciated, and read them aloud to each other.',
      'Establish a new, gentle safe word or boundary indicator for physical and emotional safety, explaining its meaning.',
      'Stand facing each other. One partner moves slowly, and the other must mirror the movements exactly, maintaining eye contact.',
      'Hold your partner tightly, placing your hand over their heart, and focus on feeling the physical heartbeat.'
    ][i % 23],
    duration: ['20 mins', '30 mins', '10 mins', '15 mins'][i % 4],
    sensoryFocus: ['Dialogue', 'Touch', 'Presence', 'Words'][i % 4],
    spiceLevel: ['Mild', 'Medium'][i % 2] as any
  })),

  // --- SURPRISE (25 entries) ---
  { id: 'i_s1', title: 'The Sneaky Shower Wash', category: 'Surprise', description: 'Surprise your partner by joining them in the shower or running a warm bath. Wash their hair, neck, and back slowly and gently, letting the warm water and slick touch build an intense bedroom expectation.', duration: '30 mins', sensoryFocus: 'Water & Touch', spiceLevel: 'Spicy' },
  { id: 'i_s2', title: 'Sticky Love Notes Scavenger', category: 'Surprise', description: 'Hide 5 small, highly flirty sticky notes in places your partner will discover throughout their day (car visor, lunchbox, wallet, laptop).', duration: '10 mins', sensoryFocus: 'Surprise', spiceLevel: 'Mild' },
  ...Array.from({ length: 23 }, (_, i) => ({
    id: `i_s_extra_${i}`,
    title: [
      'Workplace Lunch Delivery',
      'Bedtime Warm Blanket Trick',
      'Secret Bedroom Scavenger',
      'Drawer Chocolate Stash',
      'Spa Sanctuary Living Room',
      'Romantic Music Playlist Send',
      'Morning Breakfast Tray Bed',
      'Spontaneous Foot Massage',
      'Travel Thermos Chai Pack',
      'Scented Love Mail Letter',
      'Sanctuary Bedroom Bulb Swap',
      'Clean Sheets Cozy Prepare',
      'Spontaneous Office Lunch Date',
      'Sensual Descriptive Text',
      'Umbrella & Chai Rain Meet',
      'Bedside Fresh Water Glass',
      'Sensory Blindfolded Entrance',
      'Pillowcase Written Promise',
      'Warm Plush Robe Gift',
      'Indoor Forest Floor Picnic',
      'Private Custom Date Ticket',
      'Warm Towel Dryer Wrap',
      'Framed Memory Map Print'
    ][i % 23],
    category: 'Surprise' as const,
    description: [
      'Order their absolute favorite meal to be delivered to their workplace with a custom flirty message attached.',
      'While they are brushing their teeth, warm their pillowcases or blanket using a hairdryer or iron for cozy comfort.',
      'Leave clues leading them around the house, culminating in a cozy setup, a sweet gift, or an intimate invitation.',
      'Secretly buy a stash of their favorite sweet treats or snacks and hide them in their bedside drawer or cabinet.',
      'Before they come home, set up candles, massage oil, soft music, and a warm robe, inviting them to fully unwind.',
      'Create a highly specific, romantic playlist of songs that remind you of them and send it with a beautiful description.',
      'Wake up secretly, prepare a beautiful breakfast tray with fresh fruit and coffee, and surprise them in bed.',
      'While they are watching a movie or reading, gently take their feet and begin a soothing massage without them asking.',
      'Before a long drive, pack a secret bag of their favorite drive snacks and a hot thermos of coffee or tea.',
      'Write a highly sensual letter, spray it with your signature perfume or cologne, and mail it to your own address.',
      'Change the standard bedroom bulb to a soft red, amber, or purple hue, creating a premium, sensual atmosphere.',
      'Change the bedsheets to clean, fresh, crisp sheets, light a lavender candle, and lay out their comfortable sleepwear.',
      'Show up at their workplace unexpectedly during lunch hour and take them to a scenic local spot for a quick bite.',
      'Send a highly descriptive, flirty text detailing exactly what you want to do to them when they get home.',
      'If it is raining, surprise them by bringing an umbrella and a hot travel mug of tea to meet them at their car.',
      'Always place a fresh glass of cold water on their bedside table before they go to sleep, a quiet gesture of care.',
      'Blindfold your partner at the door and lead them into a room where you have set up a customized intimate experience.',
      'Write a single, beautiful promise on a small card and slide it under their pillowcase for them to find.',
      'Warm up their plush bathrobe in the dryer and present it to them on a chilly winter morning.',
      'Lay a blanket on the living room floor, light candles, and put on forest sounds for a cozy indoor picnic.',
      'Slip a custom-made, artistic ticket for a "Private Sensual Massage" or "Movie Night of Choice" under their door.',
      'Hold their towel warm by the heater while they are taking a warm shower, wrapping them in it immediately.',
      'Print out a map of where you first met, first kissed, or got engaged, framing it nicely for the bedside table.'
    ][i % 23],
    duration: ['15 mins', '30 mins', '10 mins', '5 mins'][i % 4],
    sensoryFocus: ['Surprise', 'Taste', 'Ambience', 'Touch'][i % 4],
    spiceLevel: ['Mild', 'Medium', 'Spicy'][i % 3] as any
  })),

  // --- DESIRE (25 entries) ---
  { id: 'i_de1', title: 'Forbidden Whispers (The Joint-Family Silence)', category: 'Desire', description: 'When relatives or neighbors are nearby, lock the door, turn on a low background white noise or music, and spend 30 minutes giving each other highly-arousing sensory touch and kisses. The catch: you must remain in absolute silence, communicating your desire, gasps, and pleasure strictly through intense eye contact and silent gestures.', duration: '30 mins', sensoryFocus: 'Silence & Visual Desire', spiceLevel: 'Spicy' },
  { id: 'i_de2', title: 'Traditional Saree/Drape Slow Peel', category: 'Desire', description: 'One partner wears a traditional Indian drape (like a saree or lungi/veshti). The other partner slowly, systematically, and deliberately unwinds the garment, pausing to kiss, lick, and stroke each new patch of skin that is revealed to the bedroom air.', duration: '20 mins', sensoryFocus: 'Tactile Fabric & Visual Passion', spiceLevel: 'Spicy' },
  { id: 'i_de3', title: 'Chai & Ice Contrast Touch', category: 'Desire', description: 'Prepare a warm cup of spiced cardamom tea and a bowl of ice cubes. Take a sip of the warm tea and trace your heated lips along your partner\'s neck and collarbone. Immediately follow it by gliding an ice cube slowly down their chest and inner thighs, creating a wild sensory contrast.', duration: '25 mins', sensoryFocus: 'Hot & Cold Tactile', spiceLevel: 'Spicy' },
  ...Array.from({ length: 22 }, (_, i) => ({
    id: `i_de_extra_${i}`,
    title: [
      'Blindfolded Aromatic Massage',
      'Mirror Reflection Seduction',
      'The 15-Minute Bedroom Tease',
      'Soft Silk Wrist restraints',
      'Feather-Light Collarbone Trace',
      'Erotic Poetry Shared Reading',
      'Spontaneous Secluded Car Date',
      'Pulse Sensation Neck Bites',
      'Edible Body Sweet Sauce Painting',
      'Glow-in-the-Dark Body Art Paint',
      'Blindfolded Scent Search Kiss',
      'Slick Warm Body Oil slide',
      'Under-the-Table Busy Restaurant Touch',
      'Velvet Ribbon Blindfold Trace',
      'Cardamom & Honey collarbone lick',
      'Seductive Whispered Count',
      'Traditional Lungi/Drape peel',
      'Intense Visual Stare challenge',
      'Sensory Deprivation Kissing Match',
      'Low-Temp Soy Wax massage',
      'Cold Metal Ring spine trace',
      'Midnight Steamy Sauna Shower'
    ][i % 22],
    category: 'Desire' as const,
    description: [
      'Blindfold your partner and give them a slow, sensory touch massage with fragrant warm sandalwood oil.',
      'Stand behind your partner in front of a mirror, kissing their neck while locking eyes in the reflection.',
      'Spend 15 full minutes doing nothing but touching and teasing sensitive areas without allowing any direct intercourse.',
      'Use a soft silk scarf or tie to gently secure your partner\'s wrists, exploring control and surrender in bed.',
      'Use a soft feather or your fingertips to lightly trace lines from their collarbone down to their thighs in silence.',
      'Lying in bed under dim lighting, take turns reading a highly descriptive, tasteful erotic passage aloud.',
      'Pull over in a secluded, safe, and private scenic spot late at night. Lean the seats back and explore connection.',
      'Spend 5 full minutes planting slow, suctioning, heated kisses on their neck and collarbone, leaving a soft mark.',
      'Drizzle warm chocolate or strawberry sauce on your partner\'s stomach, licking it off slowly and deliberately.',
      'Use edible or glow-in-the-dark paint to write flirty messages on each other\'s bodies, exploring with touch.',
      'Both partners are blindfolded. Find each other\'s lips, face, and collarbone purely through touch and smell.',
      'Pour fragrant bath oils into warm water. Wash each other slowly, letting your bodies slide against each other.',
      'While out at a busy restaurant, slide your hand onto their thigh under the table, holding eye contact.',
      'Blindfold your partner and trace a velvet ribbon slowly along their body, letting them guess where it is.',
      'Drizzle a little warm honey and cardamom on their collarbone and lick it off slowly, enjoying the sweet spice.',
      'Trace your fingers along their skin, counting slowly from 1 to 10. With each number, kiss a highly sensitive spot.',
      'Have your partner wear a light cotton wrap, and slowly unwrap it while placing kisses on their lower abdomen.',
      'Sit across from each other. Stare intensely into each other\'s eyes, letting your expressions communicate passion.',
      'Put earplugs in your partner\'s ears and blindfold them. Spend 10 minutes kissing them, intensifying touch.',
      'Use a low-temperature massage candle. Drizzle the warm soy wax slowly onto their back, massaging it in deeply.',
      'Trace your wedding ring or a cold metal necklace slowly along your partner\'s collarbone, chest, and stomach.',
      'Turn the bathroom into a steamy sauna. Stand together under the hot water, washing and holding each other.'
    ][i % 22],
    duration: ['30 mins', '20 mins', '15 mins', '45 mins'][i % 4],
    sensoryFocus: ['Touch', 'Visual', 'Scent', 'Taste', 'Sound'][i % 5],
    spiceLevel: ['Spicy', 'Medium'][i % 2] as any
  })),

  // --- COMFORT (10 entries) ---
  { id: 'i_co1', title: 'The Private Sanctuary Pillow fort', category: 'Comfort', description: 'Assemble a cozy mattress setup on the floor, surrounded by heavy pillows. Lounge together in a tight spooning embrace, matching your breathing patterns in absolute security.', duration: '1 hour', sensoryFocus: 'Softness & Safety', spiceLevel: 'Mild' },
  ...Array.from({ length: 9 }, (_, i) => ({
    id: `i_co_extra_${i}`,
    title: [
      'Lavender forehead rub',
      'Back-to-Back Deep Breathing',
      'Shared warm mocktail sip',
      'Sleepy hair stroking',
      'Warm essential oil basin soak',
      'Lazy afternoon spooning',
      'Face-cradling tender gaze',
      'Kitchen cuddle surprise',
      'Intimate home sanctuary talk'
    ][i % 9],
    category: 'Comfort' as const,
    description: [
      'Apply soothing oil to your partner\'s temples and gently massage them while they rest their head in your lap.',
      'Sit back-to-back. Breathe deeply and match your partner\'s respiratory rhythm, establishing a quiet, grounding bond.',
      'Brew a warm, soothing drink. Sip it together slowly, passing the cup back and forth in quiet comfort.',
      'Gently stroke your partner\'s hair and forehead using light, comforting strokes while they fall asleep.',
      'Prepare a warm basin of water with essential oils. Help your partner soak their feet, drying them gently.',
      'Spooning in absolute, quiet comfort on a weekend afternoon, with zero expectations, letting the warmth settle.',
      'Gently cradle your partner\'s face in both hands, looking at them with total tenderness and smiling softly.',
      'Surprise your partner with a slow, deep, wrapping hug from behind while they are in the kitchen.',
      'Quietly discuss: "What is the one thing about our home that makes you feel the most emotionally safe?"'
    ][i % 9],
    duration: ['20 mins', '15 mins', '30 mins', '10 mins'][i % 4],
    sensoryFocus: ['Touch', 'Scent', 'Breath', 'Warmth'][i % 4],
    spiceLevel: 'Mild' as const
  })),

  // --- ATMOSPHERE (10 entries) ---
  { id: 'i_at1', title: 'Indian Loban & Jasmine Glow', category: 'Atmosphere', description: 'Set a premium bedroom sanctuary: burn high-quality Loban (traditional incense) or Sandalwood dhoop, switch off the main bulbs, and lay out soft warm orange or red fairy lights. The sweet, traditional musk instantly transforms the room into an exotic Kama Sutra retreat.', duration: '20 mins', sensoryFocus: 'Scent & Lighting glow', spiceLevel: 'Mild' },
  ...Array.from({ length: 9 }, (_, i) => ({
    id: `i_at_extra_${i}`,
    title: [
      'Sanctuary Scent Diffuser',
      'Virtual Fireplace Crackle',
      'Dim Bedroom Tea Lights',
      'Sensual acoustic Sitars',
      'Satin Bed Sheets swap',
      'Incense & Velvet cushions',
      'Ceiling Water-Wave Projection',
      'Rose Petals Bed scatter',
      'Blindfolded Fragrance Rank'
    ][i % 9],
    category: 'Atmosphere' as const,
    description: [
      'Set up an oil diffuser with custom lavender, jasmine, or patchouli oils, creating a deeply relaxing environment.',
      'Lounge in front of a fireplace or a simulated glowing fire screen, listening to the quiet crackle and warmth.',
      'Place 15 flickering tea candles around the bedroom, casting soft, moving shadows on the walls.',
      'Curate a playlist of low-frequency, deep, bassy ambient tracks that vibrate softly through the floorboards.',
      'Swap cotton sheets for premium silk or satin sheets, noticing the slick, cool physical touch against your skin.',
      'Burn high-quality sandalwood incense and place rich velvet pillows on the bed, appealing to multiple senses.',
      'Project moving ocean light effects on the ceiling while playing soft, deep underwater sounds.',
      'Scatter edible, fragrant rose petals across the fresh sheets, making the bed space look like a luxury retreat.',
      'Blindfold your partner and introduce three distinct home fragrances (wood, citrus, floral) to see what they prefer.'
    ][i % 9],
    duration: ['15 mins', '30 mins', '1 hour', '10 mins'][i % 4],
    sensoryFocus: ['Scent', 'Visual', 'Sound', 'Touch'][i % 4],
    spiceLevel: ['Mild', 'Medium'][i % 2] as any
  }))
];

// =========================================================================
// 3. GAME DARES (105+ UNIQUE HIGH-QUALITY ADULT & INDIAN CULTURAL ENTRIES)
// =========================================================================
export const SEED_DARES: GameDare[] = [
  // --- MILD (35 entries) ---
  { id: 'gd_m1', text: "Give your partner a slow, warm hug that lasts at least 30 seconds, sync your breathing completely.", category: "Affection", spiceLevel: 'Mild' },
  { id: 'gd_m2', text: "Whisper your absolute favorite memory of our early dates in a busy Indian cafe or park.", category: "Dialogue", spiceLevel: 'Mild' },
  { id: 'gd_m3', text: "State one traditional outfit of mine that makes your heart skip a beat when you see me in it.", category: "Dialogue", spiceLevel: 'Mild' },
  ...Array.from({ length: 32 }, (_, i) => ({
    id: `gd_m_extra_${i}`,
    text: [
      "Spend 2 minutes gently playing with your partner's hair while looking into their eyes.",
      "Hold your partner's hands, lock eyes, and state three things you appreciate about their mind.",
      "Give your partner a gentle temple and forehead massage for 2 minutes using light pressure.",
      "State one secret habit of mine that you secretly find incredibly endearing.",
      "Plant a soft, lingering kiss on both of your partner's closed eyelids.",
      "Whisper the most beautiful compliment you can think of using only your eyes first, then speak it.",
      "Hold your partner close and sway slowly in the middle of the room for 1 minute in silence.",
      "Describe your partner's personality using only three distinct culinary flavors.",
      "Trace a slow, feather-light line along your partner's forearm using only your fingernails.",
      "Whisper your dream home location and layout in their ear.",
      "Give your partner a warm, comforting hug from behind while they are sitting down.",
      "Tell your partner what song instantly makes you think of them when you are alone.",
      "Gently squeeze your partner's hands three times, our private signal for 'I love you'.",
      "Trace the outline of your partner's lips slowly with your index finger.",
      "Give your partner a sweet, lingering cheek kiss that lasts at least 5 seconds.",
      "Ask your partner what color they think represents your bond today, and explain why.",
      "Trace a heart slowly onto your partner's palm, holding eye contact.",
      "Tell your partner the funniest inside joke we share, and laugh together.",
      "Gently rub your noses together in a sweet Eskimo kiss, smiling softly.",
      "Give your partner a quiet, gentle shoulder squeeze to relieve tension.",
      "Tell your partner the most romantic compliment you've ever received from them.",
      "Trace a slow circle around your partner's wrist bone with your thumb.",
      "Whisper a sweet, positive intention for your partner's upcoming week.",
      "Place a gentle kiss on your partner's forehead, holding it for 3 seconds.",
      "Tell your partner what outfit of theirs makes you feel exceptionally proud to be with them.",
      "Trace a slow line from their collarbone to their shoulder tip.",
      "Give your partner a slow, quiet back massage with their clothes on.",
      "Tell your partner three physical things you appreciate about their face.",
      "Gently trace your partner's eyebrows with your fingertips.",
      "Give your partner a sweet, playful butterfly kiss using your eyelashes against their cheek.",
      "Tell your partner a tiny, cute detail about how they sleep that you find endearing.",
      "Trace a slow, soothing infinity symbol onto your partner's forearm."
    ][i % 32],
    category: ["Affection", "Dialogue", "Touch", "Playful"][i % 4],
    spiceLevel: 'Mild' as const
  })),

  // --- MEDIUM (35 entries) ---
  { id: 'gd_me1', text: "Trace a slow path of lingering kisses along your partner's jawline, neck, and collarbone.", category: "Tease", spiceLevel: 'Medium' },
  { id: 'gd_me2', text: "Slowly feed your partner a traditional sweet, a chocolate, or a fruit with your fingers.", category: "Sensory", spiceLevel: 'Medium' },
  { id: 'gd_me3', text: "Whisper a highly flirty, adult fantasy that you haven't mentioned yet directly into their ear.", category: "Desire", spiceLevel: 'Medium' },
  ...Array.from({ length: 32 }, (_, i) => ({
    id: `gd_me_extra_${i}`,
    text: [
      "Give your partner a slow, warm 2-minute massage on their neck and shoulders using scented oil.",
      "Hold your partner's face in both hands and give them a lingering, 10-second kiss on the lips.",
      "Trace your fingers slowly along your partner's collarbone and down their ribcage.",
      "Whisper three highly seductive adjectives that describe how you feel when I touch you.",
      "Nibble gently on your partner's earlobe, followed by a warm, lingering kiss.",
      "Have your partner close their eyes and trace a velvet ribbon slowly along their neck and collar.",
      "Slowly trace your fingers up your partner's inner thighs, stopping right before the boundary.",
      "Spend 1 minute kissing your partner's neck and jawline without touching their lips.",
      "Describe your partner's sensual aura using only a temperature and a texture description.",
      "Slide your hand slowly under your partner's shirt, placing your warm palm against their bare back.",
      "Tell your partner what physical touch of theirs instantly sends a shiver down your spine.",
      "Give your partner a slow, heated hand massage using fragrant lotion, tracing every finger.",
      "Kiss your partner's pulse points on both wrists, lingering on the warmth.",
      "Whisper a flirty invitation for what you want to explore erotically this weekend.",
      "Gently blow on the back of your partner's neck, then place a soft kiss there.",
      "Hold direct eye contact for 30 seconds while slowly tracing their jawline.",
      "Slowly pull your partner close by their waist, matching your breathing patterns.",
      "Trace a slow heart symbol onto your partner's chest over their heart.",
      "Whisper the exact physical sensation you feel when my fingers run through your hair.",
      "Place a warm, lingering kiss on your partner's collarbone, holding it for 5 seconds.",
      "Gently run your fingers along the sides of your partner's waist and hips.",
      "Tell your partner which part of their body you are most attracted to right now.",
      "Kiss your partner's forehead, then cheeks, then chin, skipping the lips playsomely.",
      "Slide your fingers through your partner's fingers, holding hands tightly in a heated grip.",
      "Trace a slow line from their neck down their spine with one warm finger.",
      "Whisper a playful dare about what traditional drape outfit they should wear for you tonight.",
      "Gently bite down on your partner's lower lip during a slow kiss, followed by a soft stroke.",
      "Have your partner rest their head in your lap while you slowly massage their scalp.",
      "Gently trace your partner's shoulder blades using circular motions.",
      "Tell your partner the exact moment you felt the strongest physical chemistry between us.",
      "Gently blow on the front of your partner's neck, then plant a slow kiss.",
      "Slide your hand slowly up their spine, pulling them chest-to-chest with you."
    ][i % 32],
    category: ["Touch", "Dialogue", "Sensory", "Heat"][i % 4],
    spiceLevel: 'Medium' as const
  })),

  // --- SPICY (35 entries) ---
  { id: 'gd_s1', text: "Blindfold your partner using a soft silk scarf, and give them a slow, sensory touch massage with warm sandalwood oil on their back and thighs.", category: "Sensory", spiceLevel: 'Spicy' },
  { id: 'gd_s2', text: "Whisper in vivid detail what sexual act you want to perform on them tonight, and how you want them to respond.", category: "Passion", spiceLevel: 'Spicy' },
  { id: 'gd_s3', text: "Give your partner a 15-second neck-kissing and sucking session, leaving a warm mark on their collarbone.", category: "Intense", spiceLevel: 'Spicy' },
  { id: 'gd_s4', text: "Trace a piece of cold ice slowly down their spine, immediately following the chilling trail with your hot tongue and lips.", category: "Sensory", spiceLevel: 'Spicy' },
  { id: 'gd_s5', text: "Spend 2 full minutes kissing your partner's inner thighs, slowly moving upward until they gasp.", category: "Tease", spiceLevel: 'Spicy' },
  ...Array.from({ length: 30 }, (_, i) => ({
    id: `gd_s_extra_${i}`,
    text: [
      "Gently secure your partner's wrists using a soft tie, taking absolute control of the pace.",
      "Stand behind your partner in front of a mirror, kissing their neck while looking at the reflection.",
      "Drizzle chocolate sauce or sweet syrup onto their collarbone or stomach, slowly licking it off.",
      "Slowly undress your partner, kissing each newly revealed area of skin for 5 seconds.",
      "Spend 3 minutes in a passionate kissing session, letting your bodies press tightly together in bed.",
      "Trace a slow line from their neck down their stomach using a warm metal spoon.",
      "Whisper a highly detailed description of your favorite erotic memory of us in bed.",
      "Gently secure your partner's ankles using a soft tie, exploring full surrender.",
      "Trace a feather-light path from their chin down to their navel using your fingertips.",
      "Kiss your partner's neck, collarbone, and shoulders while slowly stroking their chest.",
      "Whisper a quiet, heated confession of what physical act turns you on the most.",
      "Trace an ice cube along their spine, immediately following it with your warm lips.",
      "Spend 2 minutes gently biting and kissing their earlobes and jawline.",
      "Perform a slow, heated thigh massage using warm oils, tracing patterns.",
      "Hold your partner's wrists gently above their head while kissing them deeply.",
      "Whisper a bold, flirty promise of what you will do to them in the shower later.",
      "Trace a slow line up their inner thigh using your lips, planting soft kisses.",
      "Drizzle warm soy wax safely onto their back, massaging it in deeply.",
      "Kiss your partner's lower back and hips, tracing the contours of their shape.",
      "Hold direct eye contact during a slow, heated kiss, letting your breathing match.",
      "Gently trace your partner's ribcage and waist using circular, heated strokes.",
      "Whisper a secret physical fantasy you want us to act out tonight.",
      "Spend 3 minutes in a passionate spooning position, exploring touch and warmth.",
      "Gently run your fingers along the back of their thighs and calves in a heated trace.",
      "Place a slow, heated kiss on their collarbone, nibbling gently before kissing again.",
      "Whisper a flirty instruction of how they should massage you later tonight.",
      "Gently tie their hands with a silk tie, kissing their neck while they are restricted.",
      "Trace a slow, heated line from their collarbone to their hip using your warm tongue.",
      "Spend 2 full minutes kissing their stomach and navel, holding their hips tightly.",
      "Sit on their lap, wrap your arms around their neck, and kiss them passionately for 1 minute."
    ][i % 30],
    category: ["Control", "Heat", "Sensory", "Passion"][i % 4],
    spiceLevel: 'Spicy' as const
  }))
];

// =========================================================================
// 4. POSITIONS LIBRARY (10 TASTEFUL KAMA SUTRA POSITIONS)
// =========================================================================
export const SEED_POSITIONS: Position[] = [
  {
    id: 'pos1',
    name: 'The Padmasana Union (Sacred Lotus)',
    description: 'A deeply sensual Kama Sutra classic. The bottom partner sits cross-legged, and the active partner sits on their lap, wrapping arms and legs tightly around them, pressing chest-to-chest. This brings faces extremely close for kissing, deep breathing, and slow, meditative pelvic movements.',
    difficulty: 'Comfortable',
    energyLevel: 'Relaxed',
    duration: 'Extended',
    sensoryFocus: 'Eye Contact & Face-to-Face whispers',
    silhouetteType: 'lotus',
    whyTry: 'Fosters intense emotional closeness, requires minimal physical effort, and matches perfectly with slow, intimate breathing.'
  },
  {
    id: 'pos2',
    name: 'Sama Pada Spooning (The Indigo Spoon)',
    description: 'A comfortable, highly relaxed lying posture. Both lie side-by-side facing the same direction, spooning closely. The active partner slides in from behind. This angle allows full physical contact and leaves the hands completely free to caress breast, stomach, and thighs.',
    difficulty: 'Beginner',
    energyLevel: 'Relaxed',
    duration: 'Medium',
    sensoryFocus: 'Bare Skin Warmth & Rhythmic caress',
    silhouetteType: 'embrace',
    whyTry: 'Perfect for sleepy mornings, quiet nights, or when energy is low but the desire for close sexual connection is high.'
  },
  {
    id: 'pos3',
    name: 'Setu Bandha Bridge (The Arching Bridge)',
    description: 'The receiving partner lies flat on their back, raising their hips (supported by a plush bolster or pillows) to form a bridge. The active partner kneels over them, creating an incredibly steep angle of entry that offers deep stimulation and amazing visual views.',
    difficulty: 'Advanced',
    energyLevel: 'Intense',
    duration: 'Short',
    sensoryFocus: 'Visuals & Deep Gaze',
    silhouetteType: 'bridge',
    whyTry: 'Provides deep G-spot or A-spot stimulation, maximizes pelvic snugness, and creates an active, heated pace.'
  },
  {
    id: 'pos4',
    name: 'Viparita Karani (The Elevated Fusion)',
    description: 'The receiving partner lies on their back, pulling knees close to the chest, elevating the pelvis slightly. The active partner slides forward, resting their body weight gently on top, creating a highly snug, full-body friction fit and direct chest-to-skin touch.',
    difficulty: 'Comfortable',
    energyLevel: 'Active',
    duration: 'Medium',
    sensoryFocus: 'Full Skin Contact & Pelvic Heat',
    silhouetteType: 'fusion',
    whyTry: 'Generates intense skin-to-skin warmth and synchronized breathing, giving a profound sense of becoming one.'
  },
  {
    id: 'pos5',
    name: 'Upavishta Ascent (The Seated Embrace)',
    description: 'One partner sits comfortable on the edge of a bed or a sturdy table. The other partner stands between their knees, holding their hips or waist. This allows absolute control over depth, pacing, and visual connection, making kissing effortless.',
    difficulty: 'Beginner',
    energyLevel: 'Active',
    duration: 'Medium',
    sensoryFocus: 'Face-to-Face & Hand Mobility',
    silhouetteType: 'ascent',
    whyTry: 'Highly comfortable with perfect angles, great for kissing, and extremely easy on the joints for long play sessions.'
  },
  {
    id: 'pos6',
    name: 'Kutila Crescent (The Crescent Moon)',
    description: 'The receiving partner lies on their stomach, hips elevated by a supportive pillow, legs together. The active partner slides over from behind. This narrow rear angle offers uniquely tight, velvet-like friction and allows direct whispers into the ear.',
    difficulty: 'Advanced',
    energyLevel: 'Relaxed',
    duration: 'Medium',
    sensoryFocus: 'Whispering & Snug Friction',
    silhouetteType: 'crescent',
    whyTry: 'Provides an intense rear-entry fullness while allowing the active partner\'s arms to wrap around and caress the receiving partner.'
  },
  {
    id: 'pos7',
    name: 'The Gentle T-Union',
    description: 'One partner lies flat on their back, while the other lies perpendicular to them, forming a T-shape. This diagonal entry reduces friction resistance, allowing extremely slow, gentle, and relaxing rhythmic movements.',
    difficulty: 'Beginner',
    energyLevel: 'Relaxed',
    duration: 'Extended',
    sensoryFocus: 'Slow strokes & Relaxed Breathing',
    silhouetteType: 'embrace',
    whyTry: 'A stable, low-effort connection that is perfect for long, meditative lovemaking sessions focused on sensory recovery.'
  },
  {
    id: 'pos8',
    name: 'The Elevated Lotus Ascent',
    description: 'A variation of the seated Lotus where the bottom partner sits on a chair or the edge of a high bed, allowing feet to rest on the ground. This drastically increases leg comfort and gives the bottom partner more dynamic control over the pelvic sway.',
    difficulty: 'Comfortable',
    energyLevel: 'Active',
    duration: 'Medium',
    sensoryFocus: 'Pelvic Sway & Eye Locking',
    silhouetteType: 'lotus',
    whyTry: 'Offers the deep, face-to-face emotional proximity of the seated Lotus but with much better leg mobility and sway control.'
  },
  {
    id: 'pos9',
    name: 'Janu Kurpara Union (Kneeling Spur)',
    description: 'The receiving partner kneels on the bed and rests their weight on their forearms, raising their hips. The active partner kneels closely behind them, aligning hips for deep, sensory rear entry. Highly exciting, visual, and rhythmic.',
    difficulty: 'Advanced',
    energyLevel: 'Intense',
    duration: 'Short',
    sensoryFocus: 'Visuals & Deep Rhythmic friction',
    silhouetteType: 'bridge',
    whyTry: 'Provides excellent depth control, direct G-spot access, and a highly exciting, active pace.'
  },
  {
    id: 'pos10',
    name: 'Yugala Spandana (Rhythmic Sway Spoon)',
    description: 'Both partners lie on their sides facing each other. The active partner raises one leg and wraps it over the other\'s hip, locking their pelvises together. This creates a very snug side spoon fit that is lazy, slow, and highly sensual.',
    difficulty: 'Comfortable',
    energyLevel: 'Relaxed',
    duration: 'Extended',
    sensoryFocus: 'Snug lock & Bedroom whispers',
    silhouetteType: 'fusion',
    whyTry: 'Allows the full-body snugness of fusion but with the lazy, side-lying relaxation of spooning, perfect for late nights.'
  }
];
